### ISSUE TITLE
Wrong date (01/01/1970)

### ISSUE THREAD

**Issue by saveman71** [ylorant/ponywalls#2]
This is the first time I notice it, but i don't think these pics are from the first hour of unix time xD

![](http://dl.dropbox.com/u/38125328/shots/1341605707.png)

It does not really matter, but it might be nice to put at least put the file date

**Comment by ylorant** [comment]
Can I have a link of one of these images, the last ones uploaded don't have this bug.

**Comment by saveman71** [comment]
@ylorant From http://ponywalls.net/view/1 to http://ponywalls.net/view/177

**Comment by ylorant** [comment]
Ok. These one were the ones _before_ the date system was introduced. So it's perfectly normal. But I'll set them to a fixed date if it's so annoying.
