### ISSUE TITLE
Improved upload process

### ISSUE THREAD

**Issue by saveman71** [ylorant/ponywalls#3]
Hello, here are some possible improvements for the upload process :
- It would be nice to be able to upload an image from a url, without having to download it before.
- Entering keywords should not be in a JS prompt.
- All specifications, as rating or source, should be submited directly from this process.
- Why not predefined lists of keywords, like i.e. "applejack rainbow_dash fluttershy pinkie_pie twilight_sparkle rarity mane_six" or "sweetie_belle scootaloo apple_bloom cmc cutie_mark_crusaders"

**Comment by ylorant** [comment]
Mmmmh, this needs a lot of adjustements. I propose another way of sending wallpapers :
1. The user posts the wallpaper, nothing else than the wall file (drag&drop or file input) is asked.
2. When the wallpaper is sent, the user is redirected to its page, and fills the data, like when editing it.
